# Generated by Django 4.0.6 on 2022-08-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exhibit', models.CharField(choices=[('전시1', '전시1'), ('전시2', '전시2'), ('전시3', '전시3')], max_length=10, null=True)),
                ('Day', models.CharField(choices=[('9월 3일', '9월 3일'), ('9월 4일', '9월 4일'), ('9월 17일', '9월 17일'), ('9월 18일', '9월 18일'), ('9월 24일', '9월 24일'), ('9월 25일', '9월 25일')], max_length=10, null=True)),
                ('Time', models.CharField(choices=[('12시', '12시'), ('13시', '13시'), ('13시 30분', '13시 30분'), ('14시', '14시'), ('15시', '15시'), ('16시', '16시'), ('16시 30분', '16시 30분'), ('17시', '17시'), ('18시', '18시')], max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
