# Generated by Django 4.0.6 on 2022-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Phone',
            field=models.TextField(null=True),
        ),
    ]
