# Generated by Django 4.0.6 on 2022-08-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_name_reservation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Exhibit',
        ),
    ]
