# Generated by Django 4.0.6 on 2022-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_reservation_exhibit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Dance',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Personal',
            field=models.BooleanField(null=True),
        ),
    ]
