# Generated by Django 4.0.6 on 2022-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation_dance_reservation_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Time',
            field=models.CharField(choices=[('12시', '12시'), ('12시 30분', '12시 30분'), ('13시', '13시'), ('13시 30분', '13시 30분'), ('14시', '14시'), ('14시 30분', '14시 30분'), ('15시', '15시'), ('15시 30분', '15시 30분'), ('16시', '16시'), ('16시 30분', '16시 30분'), ('17시', '17시'), ('17시 30분', '17시 30분'), ('18시', '18시'), ('18시 30분', '18시 30분'), ('19시', '19시'), ('19시 30분', '19시 30분'), ('20시', '20시')], max_length=10, null=True),
        ),
    ]
