# Generated by Django 4.0.6 on 2022-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Person',
            field=models.CharField(choices=[('1명', '1명'), ('2명', '2명')], max_length=10, null=True),
        ),
    ]
