# Generated by Django 4.0.6 on 2022-09-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
    ]
