# Generated by Django 4.0.6 on 2022-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_image_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
